### ISSUE TITLE
Field not encrypted when object are created from fixture

### ISSUE THREAD

**Issue by alex-dna** [lekoala/silverstripe-encrypt#7]
Hi.
I think the encryption doesn't kick in when an object is created via a fixture.
I'm using:
`$fixture = Injector::inst()->create(YamlFixture::class, $path);
        $fixture->writeInto($factory);`
and it seems like the fields that should be encrypted are not saved as such.
If I reassign the value and save the object again, it then gets encrypted.

Do you know if it is expected?

Thank you.
Alex

**Comment by lekoala** [comment]
@alex-dna that's odd. did you check the unit tests? i use fixture in them and it doesn't seem to have issues

for encryption to work automatically, you have to override the following methods and use the trait "HasEncryptedFields"

 public function getField($field)
    {
        return $this->getEncryptedField($field);
    }

    public function setField($fieldName, $val)
    {
        return $this->setEncryptedField($fieldName, $val);
    }

**Comment by alex-dna** [comment]
No worries @lekoala , it must be my set up.
Thanks.
