### ISSUE TITLE
Can't use private static $searchable_fields on encrypted fields

### ISSUE THREAD

**Issue by Sitetools** [lekoala/silverstripe-encrypt#8]
I'm testing this addon and I've come across an issue that I can't resolve.
In the CMS I have a gridfield with encrypted fields  that I want to search.
```php
    private static $db = [
        'Title' => EncryptedDBVarchar::class,
    ];

    private static $indexes = [
        'Title' => true,
    ];

   private static $searchable_fields = [
       'Title',
    ];
```
When I filter in the CMS I don't get the expected rows returned for my search parameter.
Is there a way of filtering encrypted fields in the CMS?

**Comment by lekoala** [comment]
ah yes, search in the cms requires a bit of extra work but it's doable

first thing, use the EncryptedDBField class. Other encrypted fields are NOT searchable
with EncryptedDBField , you get a blindIndex. Please note it only allows exact match (a full title, a full email, etc)
If you want partial match, you need to make partial blind indexes (for example, here https://github.com/lekoala/silverstripe-encrypt/blob/master/src/EncryptedNumberField.php if you want to search on the last 4 numbers)

then all you need to do is to tweak the model admin with something like this

```php
   public function getList()
    {
        /** @var DataList $list */
        $list = parent::getList();
        $param = $this->request->requestVar('q');

            if (isset($param['MyEncryptedField']) && $param['MyEncryptedField'] != "") {
        $singl = singleton(MyDataObject::class);
        $obj = $singl->dbObject('MyEncryptedField');
        $encrypted = $obj->getSearchValue($value, $singl);
                $list = $list->where("MyEncryptedFieldIndex = '" . $encrypted . "'");
            }
       
        return $list;
    }

    public function getSearchContext()
    {
        $context = parent::getSearchContext();

            $fields = $context->getFields();
      
            $fields->insertAfter(new TextField('q[MyEncryptedField]', 'MyEncryptedField'));
        return $context;
    }
```

**Comment by Sitetools** [comment]
Thank you @lekoala that has really moved me forward.
